### ISSUE TITLE
./install安装出错

### ISSUE THREAD

**Issue by brightgems** [philsong/bitcoin-broker#6]
# trade_service
lib/src/trade_service/tradeservice.go:714: cannot use tradeServiceProcessorPing literal (type *tradeServiceProcessorPing) as type thrift.TProcessorFunction in assignment:
        *tradeServiceProcessorPing does not implement thrift.TProcessorFunction (wrong type for Process method)
                have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)

**Comment by philsong** [comment]
fix! #[https://github.com/philsong/bitcoin-broker/commit/7efbfcb7692236e529d6985eb9378ffc1f1653c7](https://github.com/philsong/bitcoin-broker/commit/7efbfcb7692236e529d6985eb9378ffc1f1653c7)
